services:
  - type: web
    name: imgc-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 8080
    autoDeploy: true

  - type: web
    name: imgc-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    autoDeploy: true